// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/screens/context_report/widgets/quick_actions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i10;

import 'package:geolocator/geolocator.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/context_report.dart' as _i7;
import 'package:valora_app/models/saved_search.dart' as _i9;
import 'package:valora_app/models/search_history_item.dart' as _i8;
import 'package:valora_app/providers/context_report_provider.dart' as _i6;
import 'package:valora_app/services/location_service.dart' as _i3;
import 'package:valora_app/services/pdok_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePosition_0 extends _i1.SmartFake implements _i2.Position {
  _FakePosition_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i3.LocationService {
  @override
  _i4.Future<_i2.Position> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i4.Future<_i2.Position>.value(
              _FakePosition_0(this, Invocation.method(#getCurrentLocation, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Position>.value(
              _FakePosition_0(this, Invocation.method(#getCurrentLocation, [])),
            ),
          )
          as _i4.Future<_i2.Position>);
}

/// A class which mocks [PdokService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdokService extends _i1.Mock implements _i5.PdokService {
  @override
  _i4.Future<List<_i5.PdokSuggestion>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i4.Future<List<_i5.PdokSuggestion>>.value(
              <_i5.PdokSuggestion>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i5.PdokSuggestion>>.value(
                  <_i5.PdokSuggestion>[],
                ),
          )
          as _i4.Future<List<_i5.PdokSuggestion>>);

  @override
  _i4.Future<String?> reverseLookup(double? lat, double? lon) =>
      (super.noSuchMethod(
            Invocation.method(#reverseLookup, [lat, lon]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [ContextReportProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextReportProvider extends _i1.Mock
    implements _i6.ContextReportProvider {
  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i7.ContextReport> get comparisonReports =>
      (super.noSuchMethod(
            Invocation.getter(#comparisonReports),
            returnValue: <_i7.ContextReport>[],
            returnValueForMissingStub: <_i7.ContextReport>[],
          )
          as List<_i7.ContextReport>);

  @override
  Set<String> get comparisonIds =>
      (super.noSuchMethod(
            Invocation.getter(#comparisonIds),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  int get radiusMeters =>
      (super.noSuchMethod(
            Invocation.getter(#radiusMeters),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i8.SearchHistoryItem> get history =>
      (super.noSuchMethod(
            Invocation.getter(#history),
            returnValue: <_i8.SearchHistoryItem>[],
            returnValueForMissingStub: <_i8.SearchHistoryItem>[],
          )
          as List<_i8.SearchHistoryItem>);

  @override
  List<_i9.SavedSearch> get savedSearches =>
      (super.noSuchMethod(
            Invocation.getter(#savedSearches),
            returnValue: <_i9.SavedSearch>[],
            returnValueForMissingStub: <_i9.SavedSearch>[],
          )
          as List<_i9.SavedSearch>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.ContextReport? getReportById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getReportById, [id]),
            returnValueForMissingStub: null,
          )
          as _i7.ContextReport?);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setRadiusMeters(int? value) => super.noSuchMethod(
    Invocation.method(#setRadiusMeters, [value]),
    returnValueForMissingStub: null,
  );

  @override
  bool isComparing(String? query, int? radius) =>
      (super.noSuchMethod(
            Invocation.method(#isComparing, [query, radius]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> addToComparison(String? query, int? radius) =>
      (super.noSuchMethod(
            Invocation.method(#addToComparison, [query, radius]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> fetchReport(String? query, int? radius) =>
      (super.noSuchMethod(
            Invocation.method(#fetchReport, [query, radius]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void removeFromComparison(String? query, int? radius) => super.noSuchMethod(
    Invocation.method(#removeFromComparison, [query, radius]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> toggleComparison(String? query, int? radius) =>
      (super.noSuchMethod(
            Invocation.method(#toggleComparison, [query, radius]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearComparison() => super.noSuchMethod(
    Invocation.method(#clearComparison, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> loadComparisonSet() =>
      (super.noSuchMethod(
            Invocation.method(#loadComparisonSet, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isExpanded(String? category, {bool? defaultValue = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #isExpanded,
              [category],
              {#defaultValue: defaultValue},
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setExpanded(String? category, bool? expanded) => super.noSuchMethod(
    Invocation.method(#setExpanded, [category, expanded]),
    returnValueForMissingStub: null,
  );

  @override
  String? getAiInsight(String? location) =>
      (super.noSuchMethod(
            Invocation.method(#getAiInsight, [location]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  String? getAiInsightError(String? location) =>
      (super.noSuchMethod(
            Invocation.method(#getAiInsightError, [location]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  bool isAiInsightLoading(String? location) =>
      (super.noSuchMethod(
            Invocation.method(#isAiInsightLoading, [location]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> generateAiInsight(_i7.ContextReport? report) =>
      (super.noSuchMethod(
            Invocation.method(#generateAiInsight, [report]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> generate(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#generate, [input]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> clearHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromHistory(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromHistory, [query]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isSearchSaved(String? query, int? radius) =>
      (super.noSuchMethod(
            Invocation.method(#isSearchSaved, [query, radius]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> saveSearch(String? query, int? radius) =>
      (super.noSuchMethod(
            Invocation.method(#saveSearch, [query, radius]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeSavedSearch(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeSavedSearch, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleSearchAlert(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSearchAlert, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
