// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/widgets/search/search_input_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/services/pdok_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PdokService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdokService extends _i1.Mock implements _i2.PdokService {
  @override
  _i3.Future<List<_i2.PdokSuggestion>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i3.Future<List<_i2.PdokSuggestion>>.value(
              <_i2.PdokSuggestion>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i2.PdokSuggestion>>.value(
                  <_i2.PdokSuggestion>[],
                ),
          )
          as _i3.Future<List<_i2.PdokSuggestion>>);

  @override
  _i3.Future<String?> reverseLookup(double? lat, double? lon) =>
      (super.noSuchMethod(
            Invocation.method(#reverseLookup, [lat, lon]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}
