// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/widgets/search/sort_options_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:valora_app/models/listing.dart' as _i3;
import 'package:valora_app/providers/search_listings_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SearchListingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchListingsProvider extends _i1.Mock
    implements _i2.SearchListingsProvider {
  @override
  List<_i3.Listing> get listings =>
      (super.noSuchMethod(
            Invocation.getter(#listings),
            returnValue: <_i3.Listing>[],
            returnValueForMissingStub: <_i3.Listing>[],
          )
          as List<_i3.Listing>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingMore),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasNextPage =>
      (super.noSuchMethod(
            Invocation.getter(#hasNextPage),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get query =>
      (super.noSuchMethod(
            Invocation.getter(#query),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#query),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#query),
            ),
          )
          as String);

  @override
  bool get hasActiveFilters =>
      (super.noSuchMethod(
            Invocation.getter(#hasActiveFilters),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasActiveFiltersOrSort =>
      (super.noSuchMethod(
            Invocation.getter(#hasActiveFiltersOrSort),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isSortActive =>
      (super.noSuchMethod(
            Invocation.getter(#isSortActive),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setQuery(String? value) => super.noSuchMethod(
    Invocation.method(#setQuery, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void setCity(String? value) => super.noSuchMethod(
    Invocation.method(#setCity, [value]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadMore() =>
      (super.noSuchMethod(
            Invocation.method(#loadMore, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> applyFilters({
    required double? minPrice,
    required double? maxPrice,
    required String? city,
    required int? minBedrooms,
    required int? minLivingArea,
    required int? maxLivingArea,
    required double? minCompositeScore,
    required double? minSafetyScore,
    required String? sortBy,
    required String? sortOrder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#applyFilters, [], {
              #minPrice: minPrice,
              #maxPrice: maxPrice,
              #city: city,
              #minBedrooms: minBedrooms,
              #minLivingArea: minLivingArea,
              #maxLivingArea: maxLivingArea,
              #minCompositeScore: minCompositeScore,
              #minSafetyScore: minSafetyScore,
              #sortBy: sortBy,
              #sortOrder: sortOrder,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearPriceFilter() =>
      (super.noSuchMethod(
            Invocation.method(#clearPriceFilter, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearCityFilter() =>
      (super.noSuchMethod(
            Invocation.method(#clearCityFilter, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearBedroomsFilter() =>
      (super.noSuchMethod(
            Invocation.method(#clearBedroomsFilter, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearLivingAreaFilter() =>
      (super.noSuchMethod(
            Invocation.method(#clearLivingAreaFilter, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearCompositeScoreFilter() =>
      (super.noSuchMethod(
            Invocation.method(#clearCompositeScoreFilter, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearSafetyScoreFilter() =>
      (super.noSuchMethod(
            Invocation.method(#clearSafetyScoreFilter, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearSort() =>
      (super.noSuchMethod(
            Invocation.method(#clearSort, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearFilters() =>
      (super.noSuchMethod(
            Invocation.method(#clearFilters, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
