# Labeler configuration – maps file paths to PR labels
# Used by .github/workflows/label-prs.yml

backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**'

frontend:
  - changed-files:
      - any-glob-to-any-file: 'apps/flutter_app/**'

admin:
  - changed-files:
      - any-glob-to-any-file: 'apps/admin_page/**'

ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'backend/Dockerfile'
          - 'docker-compose*.yml'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*Test*/**'
          - '**/*test*'
          - '**/*spec*'
