// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/widgets/insights/insights_widgets_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/map_amenity.dart' as _i4;
import 'package:valora_app/models/map_amenity_cluster.dart' as _i9;
import 'package:valora_app/models/map_city_insight.dart' as _i3;
import 'package:valora_app/models/map_overlay.dart' as _i5;
import 'package:valora_app/models/map_overlay_tile.dart' as _i10;
import 'package:valora_app/models/map_property.dart' as _i11;
import 'package:valora_app/providers/insights_provider.dart' as _i2;
import 'package:valora_app/services/api_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [InsightsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsightsProvider extends _i1.Mock implements _i2.InsightsProvider {
  @override
  List<_i3.MapCityInsight> get cities => (super.noSuchMethod(
        Invocation.getter(#cities),
        returnValue: <_i3.MapCityInsight>[],
        returnValueForMissingStub: <_i3.MapCityInsight>[],
      ) as List<_i3.MapCityInsight>);

  @override
  List<_i4.MapAmenity> get amenities => (super.noSuchMethod(
        Invocation.getter(#amenities),
        returnValue: <_i4.MapAmenity>[],
        returnValueForMissingStub: <_i4.MapAmenity>[],
      ) as List<_i4.MapAmenity>);

  @override
  List<_i9.MapAmenityCluster> get amenityClusters => (super.noSuchMethod(
        Invocation.getter(#amenityClusters),
        returnValue: <_i9.MapAmenityCluster>[],
        returnValueForMissingStub: <_i9.MapAmenityCluster>[],
      ) as List<_i9.MapAmenityCluster>);

  @override
  List<_i5.MapOverlay> get overlays => (super.noSuchMethod(
        Invocation.getter(#overlays),
        returnValue: <_i5.MapOverlay>[],
        returnValueForMissingStub: <_i5.MapOverlay>[],
      ) as List<_i5.MapOverlay>);

  @override
  List<_i11.MapProperty> get properties => (super.noSuchMethod(
        Invocation.getter(#properties),
        returnValue: <_i11.MapProperty>[],
        returnValueForMissingStub: <_i11.MapProperty>[],
      ) as List<_i11.MapProperty>);

  @override
  List<_i10.MapOverlayTile> get overlayTiles => (super.noSuchMethod(
        Invocation.getter(#overlayTiles),
        returnValue: <_i10.MapOverlayTile>[],
        returnValueForMissingStub: <_i10.MapOverlayTile>[],
      ) as List<_i10.MapOverlayTile>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.InsightMetric get selectedMetric => (super.noSuchMethod(
        Invocation.getter(#selectedMetric),
        returnValue: _i2.InsightMetric.composite,
        returnValueForMissingStub: _i2.InsightMetric.composite,
      ) as _i2.InsightMetric);

  @override
  bool get showAmenities => (super.noSuchMethod(
        Invocation.getter(#showAmenities),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  @override
  bool get showProperties => (super.noSuchMethod(
        Invocation.getter(#showProperties),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  bool get showOverlays => (super.noSuchMethod(
        Invocation.getter(#showOverlays),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i5.MapOverlayMetric get selectedOverlayMetric => (super.noSuchMethod(
        Invocation.getter(#selectedOverlayMetric),
        returnValue: _i5.MapOverlayMetric.pricePerSquareMeter,
        returnValueForMissingStub: _i5.MapOverlayMetric.pricePerSquareMeter,
      ) as _i5.MapOverlayMetric);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void update(_i6.ApiService? apiService) => super.noSuchMethod(
        Invocation.method(
          #update,
          [apiService],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> loadInsights() => (super.noSuchMethod(
        Invocation.method(
          #loadInsights,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> fetchMapData({
    required double? minLat,
    required double? minLon,
    required double? maxLat,
    required double? maxLon,
    double? zoom = 7.5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMapData,
          [],
          {
            #minLat: minLat,
            #minLon: minLon,
            #maxLat: maxLat,
            #maxLon: maxLon,
            #zoom: zoom,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void toggleAmenities() => super.noSuchMethod(
        Invocation.method(
          #toggleAmenities,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleProperties() => super.noSuchMethod(
        Invocation.method(
          #toggleProperties,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleOverlays() => super.noSuchMethod(
        Invocation.method(
          #toggleOverlays,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOverlayMetric(_i5.MapOverlayMetric? metric) => super.noSuchMethod(
        Invocation.method(
          #setOverlayMetric,
          [metric],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setMetric(_i2.InsightMetric? metric) => super.noSuchMethod(
        Invocation.method(
          #setMetric,
          [metric],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double? getScore(_i3.MapCityInsight? city) => (super.noSuchMethod(
        Invocation.method(
          #getScore,
          [city],
        ),
        returnValueForMissingStub: null,
      ) as double?);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
