import sys

with open('apps/flutter_app/lib/screens/context_report_screen.dart', 'r') as f:
    content = f.read()

# Add import
if "import 'package:share_plus/share_plus.dart';" not in content:
    content = "import 'package:share_plus/share_plus.dart';\n" + content

# Add share button to AppBar
search_pattern = "icon: const Icon(Icons.refresh_rounded),"
replacement = search_pattern + """
                  ),
                if (report != null)
                  IconButton(
                    tooltip: 'Share Report',
                    onPressed: () => _shareReport(report),
                    icon: const Icon(Icons.share_rounded),"""
content = content.replace(search_pattern, replacement)

# Add _shareReport method to _ContextReportScreenState
method_insertion_point = '  @override\n  Widget build(BuildContext context) {'
share_method = """
  void _shareReport(report) {
    final text = '''
Valora Property Analytics: ${report.location.displayAddress}

Overall Score: ${report.compositeScore.round()}/100

Category Scores:
${report.categoryScores.entries.map((e) => '- ${e.key}: ${e.value.round()}/100').join('\n')}

Generated by Valora
''';
    Share.share(text, subject: 'Property Report: ${report.location.displayAddress}');
  }

"""
content = content.replace(method_insertion_point, share_method + method_insertion_point)

with open('apps/flutter_app/lib/screens/context_report_screen.dart', 'w') as f:
    f.write(content)
