// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/services/notification_service_coverage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/notification.dart' as _i4;
import 'package:valora_app/repositories/notification_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i2.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ValoraNotification>> getNotifications({
    bool? unreadOnly = false,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [], {
              #unreadOnly: unreadOnly,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<List<_i4.ValoraNotification>>.value(
              <_i4.ValoraNotification>[],
            ),
          )
          as _i3.Future<List<_i4.ValoraNotification>>);

  @override
  _i3.Future<int> getUnreadNotificationCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotificationCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> markNotificationAsRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationAsRead, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markAllNotificationsAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllNotificationsAsRead, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNotification(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
