// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/services/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/context_report.dart' as _i3;
import 'package:valora_app/models/listing.dart' as _i7;
import 'package:valora_app/models/listing_filter.dart' as _i6;
import 'package:valora_app/models/listing_response.dart' as _i2;
import 'package:valora_app/models/notification.dart' as _i8;
import 'package:valora_app/services/api_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeListingResponse_0 extends _i1.SmartFake
    implements _i2.ListingResponse {
  _FakeListingResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContextReport_1 extends _i1.SmartFake implements _i3.ContextReport {
  _FakeContextReport_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> healthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#healthCheck, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.ListingResponse> getListings(_i6.ListingFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#getListings, [filter]),
            returnValue: _i5.Future<_i2.ListingResponse>.value(
              _FakeListingResponse_0(
                this,
                Invocation.method(#getListings, [filter]),
              ),
            ),
          )
          as _i5.Future<_i2.ListingResponse>);

  @override
  _i5.Future<_i7.Listing?> getListing(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getListing, [id]),
            returnValue: _i5.Future<_i7.Listing?>.value(),
          )
          as _i5.Future<_i7.Listing?>);

  @override
  _i5.Future<_i3.ContextReport> getContextReport(
    String? input, {
    int? radiusMeters = 1000,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getContextReport,
              [input],
              {#radiusMeters: radiusMeters},
            ),
            returnValue: _i5.Future<_i3.ContextReport>.value(
              _FakeContextReport_1(
                this,
                Invocation.method(
                  #getContextReport,
                  [input],
                  {#radiusMeters: radiusMeters},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.ContextReport>);

  @override
  _i5.Future<List<_i8.ValoraNotification>> getNotifications({
    bool? unreadOnly = false,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, [], {
              #unreadOnly: unreadOnly,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i8.ValoraNotification>>.value(
              <_i8.ValoraNotification>[],
            ),
          )
          as _i5.Future<List<_i8.ValoraNotification>>);

  @override
  _i5.Future<int> getUnreadNotificationCount() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadNotificationCount, []),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> markNotificationAsRead(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationAsRead, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markAllNotificationsAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllNotificationsAsRead, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteNotification(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
