// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/widgets/report/context_report_input_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/context_report.dart' as _i5;
import 'package:valora_app/models/search_history_item.dart' as _i3;
import 'package:valora_app/providers/context_report_provider.dart' as _i2;
import 'package:valora_app/services/pdok_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ContextReportProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextReportProvider extends _i1.Mock
    implements _i2.ContextReportProvider {
  MockContextReportProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get radiusMeters => (super.noSuchMethod(
        Invocation.getter(#radiusMeters),
        returnValue: 0,
      ) as int);

  @override
  List<_i3.SearchHistoryItem> get history => (super.noSuchMethod(
        Invocation.getter(#history),
        returnValue: <_i3.SearchHistoryItem>[],
      ) as List<_i3.SearchHistoryItem>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRadiusMeters(int? value) => super.noSuchMethod(
        Invocation.method(
          #setRadiusMeters,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isExpanded(
    String? category, {
    bool? defaultValue = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isExpanded,
          [category],
          {#defaultValue: defaultValue},
        ),
        returnValue: false,
      ) as bool);

  @override
  void setExpanded(
    String? category,
    bool? expanded,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setExpanded,
          [
            category,
            expanded,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String? getAiInsight(String? location) =>
      (super.noSuchMethod(Invocation.method(
        #getAiInsight,
        [location],
      )) as String?);

  @override
  String? getAiInsightError(String? location) =>
      (super.noSuchMethod(Invocation.method(
        #getAiInsightError,
        [location],
      )) as String?);

  @override
  bool isAiInsightLoading(String? location) => (super.noSuchMethod(
        Invocation.method(
          #isAiInsightLoading,
          [location],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> generateAiInsight(_i5.ContextReport? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAiInsight,
          [report],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> generate(String? input) => (super.noSuchMethod(
        Invocation.method(
          #generate,
          [input],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromHistory(String? query) => (super.noSuchMethod(
        Invocation.method(
          #removeFromHistory,
          [query],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PdokService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPdokService extends _i1.Mock implements _i7.PdokService {
  MockPdokService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.PdokSuggestion>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i7.PdokSuggestion>>.value(<_i7.PdokSuggestion>[]),
      ) as _i4.Future<List<_i7.PdokSuggestion>>);

  @override
  _i4.Future<String?> reverseLookup(
    double? lat,
    double? lon,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reverseLookup,
          [
            lat,
            lon,
          ],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}
