// <auto-generated />
using Valora.Infrastructure.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Valora.Infrastructure.Migrations
{
    [DbContext(typeof(ValoraDbContext))]
    [Migration("20260224000000_MakeActivityLogWorkspaceIdNullable")]
    partial class MakeActivityLogWorkspaceIdNullable
    {
    }
}
