// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/providers/ai_chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/ai_chat_message.dart' as _i5;
import 'package:valora_app/models/ai_conversation.dart' as _i4;
import 'package:valora_app/services/ai_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiService extends _i1.Mock implements _i2.AiService {
  @override
  _i3.Future<List<_i4.AiConversation>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i3.Future<List<_i4.AiConversation>>.value(
              <_i4.AiConversation>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.AiConversation>>.value(
                  <_i4.AiConversation>[],
                ),
          )
          as _i3.Future<List<_i4.AiConversation>>);

  @override
  _i3.Future<List<_i5.AiChatMessage>> getMessages(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [conversationId]),
            returnValue: _i3.Future<List<_i5.AiChatMessage>>.value(
              <_i5.AiChatMessage>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i5.AiChatMessage>>.value(
                  <_i5.AiChatMessage>[],
                ),
          )
          as _i3.Future<List<_i5.AiChatMessage>>);

  @override
  _i3.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> sendMessage({
    String? conversationId,
    required String? prompt,
    String? intent = 'chat',
    List<_i5.AiChatMessage>? history,
    Map<String, dynamic>? contextReport,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #conversationId: conversationId,
              #prompt: prompt,
              #intent: intent,
              #history: history,
              #contextReport: contextReport,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
