// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/providers/context_report_provider_comparison_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:valora_app/models/context_report.dart' as _i2;
import 'package:valora_app/models/search_history_item.dart' as _i8;
import 'package:valora_app/repositories/ai_repository.dart' as _i5;
import 'package:valora_app/repositories/context_report_repository.dart' as _i3;
import 'package:valora_app/services/search_history_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContextReport_0 extends _i1.SmartFake implements _i2.ContextReport {
  _FakeContextReport_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContextReportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextReportRepository extends _i1.Mock
    implements _i3.ContextReportRepository {
  MockContextReportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ContextReport> getContextReport(
    String? input, {
    int? radiusMeters = 1000,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getContextReport,
              [input],
              {#radiusMeters: radiusMeters},
            ),
            returnValue: _i4.Future<_i2.ContextReport>.value(
              _FakeContextReport_0(
                this,
                Invocation.method(
                  #getContextReport,
                  [input],
                  {#radiusMeters: radiusMeters},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ContextReport>);
}

/// A class which mocks [AiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiRepository extends _i1.Mock implements _i5.AiRepository {
  MockAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> getAiAnalysis(_i2.ContextReport? report) =>
      (super.noSuchMethod(
            Invocation.method(#getAiAnalysis, [report]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAiAnalysis, [report]),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [SearchHistoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchHistoryService extends _i1.Mock
    implements _i7.SearchHistoryService {
  MockSearchHistoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i8.SearchHistoryItem>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i4.Future<List<_i8.SearchHistoryItem>>.value(
              <_i8.SearchHistoryItem>[],
            ),
          )
          as _i4.Future<List<_i8.SearchHistoryItem>>);

  @override
  _i4.Future<void> addToHistory(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#addToHistory, [query]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromHistory(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromHistory, [query]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
