// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/providers/insights_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/map_amenity.dart' as _i5;
import 'package:valora_app/models/map_amenity_cluster.dart' as _i6;
import 'package:valora_app/models/map_city_insight.dart' as _i4;
import 'package:valora_app/models/map_overlay.dart' as _i7;
import 'package:valora_app/models/map_overlay_tile.dart' as _i8;
import 'package:valora_app/repositories/map_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MapRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapRepository extends _i1.Mock implements _i2.MapRepository {
  MockMapRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MapCityInsight>> getCityInsights({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCityInsights, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i3.Future<List<_i4.MapCityInsight>>.value(
              <_i4.MapCityInsight>[],
            ),
          )
          as _i3.Future<List<_i4.MapCityInsight>>);

  @override
  void invalidateCityInsightsCache() => super.noSuchMethod(
    Invocation.method(#invalidateCityInsightsCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<List<_i5.MapAmenity>> getMapAmenities({
    required double? minLat,
    required double? minLon,
    required double? maxLat,
    required double? maxLon,
    List<String>? types,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMapAmenities, [], {
              #minLat: minLat,
              #minLon: minLon,
              #maxLat: maxLat,
              #maxLon: maxLon,
              #types: types,
            }),
            returnValue: _i3.Future<List<_i5.MapAmenity>>.value(
              <_i5.MapAmenity>[],
            ),
          )
          as _i3.Future<List<_i5.MapAmenity>>);

  @override
  _i3.Future<List<_i6.MapAmenityCluster>> getMapAmenityClusters({
    required double? minLat,
    required double? minLon,
    required double? maxLat,
    required double? maxLon,
    required double? zoom,
    List<String>? types,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMapAmenityClusters, [], {
              #minLat: minLat,
              #minLon: minLon,
              #maxLat: maxLat,
              #maxLon: maxLon,
              #zoom: zoom,
              #types: types,
            }),
            returnValue: _i3.Future<List<_i6.MapAmenityCluster>>.value(
              <_i6.MapAmenityCluster>[],
            ),
          )
          as _i3.Future<List<_i6.MapAmenityCluster>>);

  @override
  _i3.Future<List<_i7.MapOverlay>> getMapOverlays({
    required double? minLat,
    required double? minLon,
    required double? maxLat,
    required double? maxLon,
    required String? metric,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMapOverlays, [], {
              #minLat: minLat,
              #minLon: minLon,
              #maxLat: maxLat,
              #maxLon: maxLon,
              #metric: metric,
            }),
            returnValue: _i3.Future<List<_i7.MapOverlay>>.value(
              <_i7.MapOverlay>[],
            ),
          )
          as _i3.Future<List<_i7.MapOverlay>>);

  @override
  _i3.Future<List<_i8.MapOverlayTile>> getMapOverlayTiles({
    required double? minLat,
    required double? minLon,
    required double? maxLat,
    required double? maxLon,
    required double? zoom,
    required String? metric,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMapOverlayTiles, [], {
              #minLat: minLat,
              #minLon: minLon,
              #maxLat: maxLat,
              #maxLon: maxLon,
              #zoom: zoom,
              #metric: metric,
            }),
            returnValue: _i3.Future<List<_i8.MapOverlayTile>>.value(
              <_i8.MapOverlayTile>[],
            ),
          )
          as _i3.Future<List<_i8.MapOverlayTile>>);
}
