// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/providers/search_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/listing.dart' as _i6;
import 'package:valora_app/models/listing_filter.dart' as _i5;
import 'package:valora_app/models/listing_response.dart' as _i2;
import 'package:valora_app/services/api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeListingResponse_0 extends _i1.SmartFake
    implements _i2.ListingResponse {
  _FakeListingResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> healthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#healthCheck, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.ListingResponse> getListings(_i5.ListingFilter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#getListings, [filter]),
            returnValue: _i4.Future<_i2.ListingResponse>.value(
              _FakeListingResponse_0(
                this,
                Invocation.method(#getListings, [filter]),
              ),
            ),
          )
          as _i4.Future<_i2.ListingResponse>);

  @override
  _i4.Future<_i6.Listing?> getListing(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getListing, [id]),
            returnValue: _i4.Future<_i6.Listing?>.value(),
          )
          as _i4.Future<_i6.Listing?>);

  @override
  _i4.Future<void> triggerLimitedScrape(String? region, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#triggerLimitedScrape, [region, limit]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
