// Mocks generated by Mockito 5.4.4 from annotations
// in valora_app/test/providers/workspace_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/comment.dart' as _i9;
import 'package:valora_app/models/saved_listing.dart' as _i8;
import 'package:valora_app/models/workspace.dart' as _i3;
import 'package:valora_app/models/activity_log.dart' as _i10;
import 'package:valora_app/repositories/workspace_repository.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkspace_0 extends _i1.SmartFake implements _i3.Workspace {
  _FakeWorkspace_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WorkspaceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceRepository extends _i1.Mock
    implements _i5.WorkspaceRepository {
  MockWorkspaceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i3.Workspace>> fetchWorkspaces() => (super.noSuchMethod(
        Invocation.method(
          #fetchWorkspaces,
          [],
        ),
        returnValue: _i6.Future<List<_i3.Workspace>>.value(<_i3.Workspace>[]),
      ) as _i6.Future<List<_i3.Workspace>>);

  @override
  _i6.Future<_i3.Workspace> createWorkspace(
    String? name,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWorkspace,
          [
            name,
            description,
          ],
        ),
        returnValue: _i6.Future<_i3.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #createWorkspace,
            [
              name,
              description,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Workspace>);

  @override
  _i6.Future<_i3.Workspace> getWorkspace(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getWorkspace,
          [id],
        ),
        returnValue: _i6.Future<_i3.Workspace>.value(_FakeWorkspace_0(
          this,
          Invocation.method(
            #getWorkspace,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.Workspace>);

  @override
  _i6.Future<void> deleteWorkspace(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkspace,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.WorkspaceMember>> getWorkspaceMembers(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkspaceMembers,
          [id],
        ),
        returnValue: _i6.Future<List<_i3.WorkspaceMember>>.value(
            <_i3.WorkspaceMember>[]),
      ) as _i6.Future<List<_i3.WorkspaceMember>>);

  @override
  _i6.Future<List<_i8.SavedListing>> getWorkspaceListings(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkspaceListings,
          [id],
        ),
        returnValue:
            _i6.Future<List<_i8.SavedListing>>.value(<_i8.SavedListing>[]),
      ) as _i6.Future<List<_i8.SavedListing>>);

  @override
  _i6.Future<List<_i10.ActivityLog>> getWorkspaceActivity(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorkspaceActivity,
          [id],
        ),
        returnValue:
            _i6.Future<List<_i10.ActivityLog>>.value(<_i10.ActivityLog>[]),
      ) as _i6.Future<List<_i10.ActivityLog>>);

  @override
  _i6.Future<void> inviteMember(
    String? workspaceId,
    String? email,
    String? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #inviteMember,
          [
            workspaceId,
            email,
            role,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveListing(
    String? workspaceId,
    String? listingId,
    String? notes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveListing,
          [
            workspaceId,
            listingId,
            notes,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addComment(
    String? workspaceId,
    String? listingId,
    String? content,
    String? parentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [
            workspaceId,
            listingId,
            content,
            parentId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.Comment>> fetchComments(
    String? workspaceId,
    String? listingId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchComments,
          [
            workspaceId,
            listingId,
          ],
        ),
        returnValue: _i6.Future<List<_i9.Comment>>.value(<_i9.Comment>[]),
      ) as _i6.Future<List<_i9.Comment>>);
}
