// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/providers/workspace_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:flutter/foundation.dart' as _i5;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:valora_app/services/api_client.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T> extends _i1.SmartFake implements _i2.Future<T> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeException_2 extends _i1.SmartFake implements Exception {
  _FakeException_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ApiRunner get runner =>
      (super.noSuchMethod(
            Invocation.getter(#runner),
            returnValue:
                <Q, R>(
                  _i5.ComputeCallback<Q, R> callback,
                  Q message, {
                  String? debugLabel,
                }) =>
                    _i6.ifNotNull(
                      _i6.dummyValueOrNull<R>(this, Invocation.getter(#runner)),
                      (R v) => _i2.Future<R>.value(v),
                    ) ??
                    _FakeFuture_0<R>(this, Invocation.getter(#runner)),
          )
          as _i4.ApiRunner);

  @override
  _i3.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_1(this, Invocation.getter(#client)),
          )
          as _i3.Client);

  @override
  T handleResponse<T>(_i3.Response? response, T Function(String)? parser) =>
      (super.noSuchMethod(
            Invocation.method(#handleResponse, [response, parser]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#handleResponse, [response, parser]),
            ),
          )
          as T);

  @override
  Exception handleException(dynamic error, StackTrace? stack, [Uri? uri]) =>
      (super.noSuchMethod(
            Invocation.method(#handleException, [error, stack, uri]),
            returnValue: _FakeException_2(
              this,
              Invocation.method(#handleException, [error, stack, uri]),
            ),
          )
          as Exception);

  @override
  _i2.Future<dynamic> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #timeout: timeout},
            ),
            returnValue: _i2.Future<dynamic>.value(),
          )
          as _i2.Future<dynamic>);

  @override
  _i2.Future<dynamic> post(
    String? path,
    dynamic data, {
    Duration? timeout,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path, data],
              {#timeout: timeout, #retry: retry},
            ),
            returnValue: _i2.Future<dynamic>.value(),
          )
          as _i2.Future<dynamic>);

  @override
  _i2.Future<dynamic> delete(
    String? path, {
    Duration? timeout,
    bool? retry = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {#timeout: timeout, #retry: retry},
            ),
            returnValue: _i2.Future<dynamic>.value(),
          )
          as _i2.Future<dynamic>);

  @override
  _i2.Future<_i3.Response> requestWithRetry(
    _i2.Future<_i3.Response> Function()? requestFn, {
    bool? retryOnError = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestWithRetry,
              [requestFn],
              {#retryOnError: retryOnError},
            ),
            returnValue: _i2.Future<_i3.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #requestWithRetry,
                  [requestFn],
                  {#retryOnError: retryOnError},
                ),
              ),
            ),
          )
          as _i2.Future<_i3.Response>);

  @override
  _i2.Future<_i3.Response> authenticatedRequest(
    _i2.Future<_i3.Response> Function(Map<String, String>)? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#authenticatedRequest, [request]),
            returnValue: _i2.Future<_i3.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#authenticatedRequest, [request]),
              ),
            ),
          )
          as _i2.Future<_i3.Response>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.Future<bool> healthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#healthCheck, []),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);
}
