using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.Net.Http.Headers;
using Valora.Api.Filters;
using Valora.Application.Common.Interfaces;
using Valora.Application.DTOs.Map;
using Valora.Application.DTOs.Shared;

namespace Valora.Api.Endpoints;

public static class MapEndpoints
{
    public static RouteGroupBuilder MapMapEndpoints(this IEndpointRouteBuilder routes)
    {
        var group = routes.MapGroup("/api/map")
            .RequireRateLimiting(Valora.Api.Constants.RateLimitPolicies.Strict)
            .WithTags("Map");

        group.MapGet("/cities", GetCityInsightsHandler)
            .RequireAuthorization()
            .WithName("GetCityInsights");

        group.MapGet("/city-insights", GetCityInsightsHandler)
            .RequireAuthorization()
            .WithName("GetCityInsightsAlias");

        group.MapGet("/amenities", GetMapAmenitiesHandler)
            .RequireAuthorization()
            .WithName("GetMapAmenities")
            .AddEndpointFilter<ValidationFilter<BoundsRequest>>();

        group.MapGet("/amenities/clusters", GetMapAmenityClustersHandler)
            .RequireAuthorization()
            .WithName("GetMapAmenityClusters")
            .AddEndpointFilter<ValidationFilter<BoundsRequest>>();

        group.MapGet("/overlays", GetMapOverlaysHandler)
            .RequireAuthorization()
            .WithName("GetMapOverlays")
            .AddEndpointFilter<ValidationFilter<BoundsRequest>>();

        group.MapGet("/overlays/tiles", GetMapOverlayTilesHandler)
            .RequireAuthorization()
            .WithName("GetMapOverlayTiles")
            .AddEndpointFilter<ValidationFilter<BoundsRequest>>();

        return group;
    }

    /// <summary>
    /// Gets aggregated insights for cities, such as average scores across neighborhoods.
    /// </summary>
    /// <remarks>
    /// Allows brief client-side caching because city insights are generated by batch jobs that run infrequently (at most every 30 mins).
    /// </remarks>
    public static async Task<IResult> GetCityInsightsHandler(IMapService mapService, HttpContext httpContext, CancellationToken ct)
    {
        var insights = await mapService.GetCityInsightsAsync(ct);
        // City insights change at most every 30 min (batch job cadence); allow brief client-side caching.
        httpContext.Response.GetTypedHeaders().CacheControl = new CacheControlHeaderValue
        {
            Public = true,
            MaxAge = TimeSpan.FromMinutes(5),
        };
        return Results.Ok(insights);
    }

    /// <summary>
    /// Gets raw amenities within a bounding box.
    /// </summary>
    /// <remarks>
    /// Allows 10-minute client caching to reduce map dragging latency.
    /// Note: Prefer `GetMapAmenityClustersHandler` for zoomed-out views to prevent sending massive raw geometry datasets.
    /// </remarks>
    public static async Task<IResult> GetMapAmenitiesHandler(
        [AsParameters] BoundsRequest bounds,
        [FromQuery] string? types,
        IMapService mapService,
        HttpContext httpContext,
        CancellationToken ct)
    {
        var typeList = ParseTypes(types);
        var amenities = await mapService.GetMapAmenitiesAsync(bounds.MinLat, bounds.MinLon, bounds.MaxLat, bounds.MaxLon, typeList, ct);
        
        httpContext.Response.Headers[HeaderNames.CacheControl] = new CacheControlHeaderValue
        {
            Public = true,
            MaxAge = TimeSpan.FromMinutes(10)
        }.ToString();

        return TypedResults.Ok(amenities);
    }

    /// <summary>
    /// Gets clustered amenities within a bounding box for performance optimization.
    /// </summary>
    /// <remarks>
    /// <strong>Architecture Decision:</strong> Clustering is performed server-side into discrete grid buckets depending on zoom level.
    /// This prevents sending raw vector data that would cause UI lag or app crashes in the Flutter client for zoomed-out map views.
    /// </remarks>
    public static async Task<IResult> GetMapAmenityClustersHandler(
        [AsParameters] BoundsRequest bounds,
        [FromQuery] double zoom,
        [FromQuery] string? types,
        IMapService mapService,
        HttpContext httpContext,
        CancellationToken ct)
    {
        var typeList = ParseTypes(types);
        var clusters = await mapService.GetMapAmenityClustersAsync(bounds.MinLat, bounds.MinLon, bounds.MaxLat, bounds.MaxLon, zoom, typeList, ct);
        
        httpContext.Response.Headers[HeaderNames.CacheControl] = new CacheControlHeaderValue
        {
            Public = true,
            MaxAge = TimeSpan.FromMinutes(10)
        }.ToString();

        return TypedResults.Ok(clusters);
    }

    /// <summary>
    /// Gets raw neighborhood metric overlays.
    /// </summary>
    public static async Task<IResult> GetMapOverlaysHandler(
        [AsParameters] BoundsRequest bounds,
        [FromQuery] MapOverlayMetric metric,
        IMapService mapService,
        HttpContext httpContext,
        CancellationToken ct)
    {
        var overlays = await mapService.GetMapOverlaysAsync(bounds.MinLat, bounds.MinLon, bounds.MaxLat, bounds.MaxLon, metric, ct);
        
        httpContext.Response.Headers[HeaderNames.CacheControl] = new CacheControlHeaderValue
        {
            Public = true,
            MaxAge = TimeSpan.FromMinutes(10)
        }.ToString();

        return TypedResults.Ok(overlays);
    }

    /// <summary>
    /// Gets rasterized tile representations of map metric overlays for efficient rendering.
    /// </summary>
    /// <remarks>
    /// <strong>Architecture Decision:</strong> Instead of sending complex neighborhood polygons (GeoJSON) which cause severe client-side
    /// stuttering, geometries are rasterized server-side into square grid tiles based on the map zoom level.
    /// </remarks>
    public static async Task<IResult> GetMapOverlayTilesHandler(
        [AsParameters] BoundsRequest bounds,
        [FromQuery] double zoom,
        [FromQuery] MapOverlayMetric metric,
        IMapService mapService,
        HttpContext httpContext,
        CancellationToken ct)
    {
        var tiles = await mapService.GetMapOverlayTilesAsync(bounds.MinLat, bounds.MinLon, bounds.MaxLat, bounds.MaxLon, zoom, metric, ct);

        // Cache for 10 minutes
        httpContext.Response.Headers[HeaderNames.CacheControl] = new CacheControlHeaderValue
        {
            Public = true,
            MaxAge = TimeSpan.FromMinutes(10)
        }.ToString();

        return TypedResults.Ok(tiles);
    }
    private static List<string>? ParseTypes(string? types)
    {
        return types?.Split(',', StringSplitOptions.RemoveEmptyEntries)
            .Select(t => t.Trim())
            .ToList();
    }
}
