// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/widgets/valora_listing_card_horizontal_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/listing.dart' as _i3;
import 'package:valora_app/providers/favorites_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavoritesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesProvider extends _i1.Mock implements _i2.FavoritesProvider {
  MockFavoritesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Listing> get favorites =>
      (super.noSuchMethod(
            Invocation.getter(#favorites),
            returnValue: <_i3.Listing>[],
          )
          as List<_i3.Listing>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  DateTime? savedAtFor(String? listingId) =>
      (super.noSuchMethod(Invocation.method(#savedAtFor, [listingId]))
          as DateTime?);

  @override
  _i4.Future<void> loadFavorites() =>
      (super.noSuchMethod(
            Invocation.method(#loadFavorites, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isFavorite(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [id]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> toggleFavorite(_i3.Listing? listing) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [listing]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
