// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/widgets/workspaces/workspace_list_item_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:valora_app/models/activity_log.dart' as _i5;
import 'package:valora_app/models/comment.dart' as _i7;
import 'package:valora_app/models/saved_property.dart' as _i4;
import 'package:valora_app/models/workspace.dart' as _i3;
import 'package:valora_app/providers/workspace_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WorkspaceProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkspaceProvider extends _i1.Mock implements _i2.WorkspaceProvider {
  MockWorkspaceProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Workspace> get workspaces =>
      (super.noSuchMethod(
            Invocation.getter(#workspaces),
            returnValue: <_i3.Workspace>[],
          )
          as List<_i3.Workspace>);

  @override
  bool get isWorkspacesLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isWorkspacesLoading),
            returnValue: false,
          )
          as bool);

  @override
  bool get isWorkspaceDetailLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isWorkspaceDetailLoading),
            returnValue: false,
          )
          as bool);

  @override
  bool get isDeletingWorkspace =>
      (super.noSuchMethod(
            Invocation.getter(#isDeletingWorkspace),
            returnValue: false,
          )
          as bool);

  @override
  List<_i3.WorkspaceMember> get members =>
      (super.noSuchMethod(
            Invocation.getter(#members),
            returnValue: <_i3.WorkspaceMember>[],
          )
          as List<_i3.WorkspaceMember>);

  @override
  List<_i4.SavedProperty> get savedProperties =>
      (super.noSuchMethod(
            Invocation.getter(#savedProperties),
            returnValue: <_i4.SavedProperty>[],
          )
          as List<_i4.SavedProperty>);

  @override
  List<_i5.ActivityLog> get activityLogs =>
      (super.noSuchMethod(
            Invocation.getter(#activityLogs),
            returnValue: <_i5.ActivityLog>[],
          )
          as List<_i5.ActivityLog>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> fetchWorkspaces() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWorkspaces, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createWorkspace(String? name, String? description) =>
      (super.noSuchMethod(
            Invocation.method(#createWorkspace, [name, description]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteWorkspace(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkspace, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> selectWorkspace(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#selectWorkspace, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> inviteMember(String? email, _i3.WorkspaceRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#inviteMember, [email, role]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveProperty(String? propertyId, String? notes) =>
      (super.noSuchMethod(
            Invocation.method(#saveProperty, [propertyId, notes]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addComment(
    String? savedPropertyId,
    String? content,
    String? parentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [
              savedPropertyId,
              content,
              parentId,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i7.Comment>> fetchComments(String? savedPropertyId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchComments, [savedPropertyId]),
            returnValue: _i6.Future<List<_i7.Comment>>.value(<_i7.Comment>[]),
          )
          as _i6.Future<List<_i7.Comment>>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
