// Mocks generated by Mockito 5.4.6 from annotations
// in valora_app/test/repositories/workspace_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:valora_app/services/api_client.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void updateAuthToken(String? token) => super.noSuchMethod(
    Invocation.method(#updateAuthToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i2.Response> request(
    String? method,
    String? path, {
    Map<String, dynamic>? queryParameters,
    dynamic data,
    Map<String, String>? headers,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [method, path],
              {
                #queryParameters: queryParameters,
                #data: data,
                #headers: headers,
                #timeout: timeout,
              },
            ),
            returnValue: _i3.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #request,
                  [method, path],
                  {
                    #queryParameters: queryParameters,
                    #data: data,
                    #headers: headers,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #headers: headers},
            ),
            returnValue: _i3.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters, #headers: headers},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
                #timeout: timeout,
              },
            ),
            returnValue: _i3.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #headers: headers,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> put(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
              },
            ),
            returnValue: _i3.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i2.Response>);

  @override
  _i3.Future<_i2.Response> delete(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #headers: headers,
              },
            ),
            returnValue: _i3.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i2.Response>);

  @override
  _i3.Future<T> handleResponse<T>(
    _i2.Response? response,
    T Function(String)? parser,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleResponse, [response, parser]),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#handleResponse, [response, parser]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_1<T>(
                  this,
                  Invocation.method(#handleResponse, [response, parser]),
                ),
          )
          as _i3.Future<T>);
}
